package com.zzy.ksongfloat.ai;
import okhttp3.*; import org.json.*; import java.io.*; import java.net.*; import java.util.concurrent.TimeUnit; import javax.net.ssl.SSLException;
public class AiClient { private volatile Call current; public interface Callback{ void onState(AiRequestState s,String msg); void onResult(AiCallResult r); }
 public void cancel(){ Call c=current; if(c!=null)c.cancel(); }
 public void chatAsync(final AiRequest req, final Callback cb){ new Thread(()->{ if(cb!=null)cb.onState(AiRequestState.CONNECTING,"正在连接 AI..."); AiCallResult r=chat(req,false); if(!r.success && shouldRetryMaxCompletion(r)){ if(cb!=null)cb.onState(AiRequestState.REQUESTING,"正在重试：将 max_tokens 切换为 max_completion_tokens..."); r=chat(new AiRequest(req.url,req.apiKey,req.body.replace("\"max_tokens\"","\"max_completion_tokens\""),req.timeoutSeconds),true);} if(cb!=null)cb.onResult(r); },"ai-chat").start(); }
 public AiCallResult chat(AiRequest req, boolean retried){ long st=System.currentTimeMillis(); try{ OkHttpClient client=new OkHttpClient.Builder().connectTimeout(req.timeoutSeconds,TimeUnit.SECONDS).readTimeout(req.timeoutSeconds,TimeUnit.SECONDS).writeTimeout(req.timeoutSeconds,TimeUnit.SECONDS).build(); Request request=new Request.Builder().url(req.url).header("Authorization","Bearer "+req.apiKey).header("Content-Type","application/json").post(RequestBody.create(req.body,MediaType.parse("application/json; charset=utf-8"))).build(); current=client.newCall(request); Response resp=current.execute(); String body=resp.body()==null?"":resp.body().string(); int code=resp.code(); long ms=System.currentTimeMillis()-st; if(!resp.isSuccessful()) return AiCallResult.fail(mapHttp(code,body)); String content=extractContent(body); if(content.isEmpty()) return AiCallResult.fail(new AiError("EMPTY_RESPONSE","空响应","AI 没有返回可解析内容",code)); String model=""; try{model=new JSONObject(body).optString("model","");}catch(Exception ignored){} return AiCallResult.ok(new AiResponse(code,content,limit(body,300),model,ms)); }catch(SocketTimeoutException e){return AiCallResult.fail(new AiError("TIMEOUT","请求超时","请检查网络或调大超时时间",0));}catch(UnknownHostException e){return AiCallResult.fail(new AiError("DNS","DNS 解析失败","请检查 Base URL",0));}catch(SSLException e){return AiCallResult.fail(new AiError("SSL","SSL 错误","请检查 HTTPS 证书或接口地址",0));}catch(IOException e){ if(e.getMessage()!=null&&e.getMessage().toLowerCase().contains("canceled")) return AiCallResult.fail(new AiError("CANCELLED","请求已取消","",0)); return AiCallResult.fail(new AiError("NETWORK","网络错误："+e.getMessage(),"请检查网络",0));}catch(Exception e){return AiCallResult.fail(new AiError("UNKNOWN","AI 请求异常："+e.getMessage(),"请检查设置",0));} finally{current=null;} }
 private String extractContent(String body)throws JSONException{ JSONObject o=new JSONObject(body); JSONArray cs=o.optJSONArray("choices"); if(cs==null||cs.length()==0)return""; JSONObject msg=cs.optJSONObject(0).optJSONObject("message"); return msg==null?"":msg.optString("content",""); }
 private boolean shouldRetryMaxCompletion(AiCallResult r){ if(r==null||r.success||r.error==null)return false; String m=(r.error.message+" "+r.error.suggestion).toLowerCase(); return m.contains("max_tokens")&&(m.contains("unsupported")||m.contains("unknown")||m.contains("not support")); }
 private AiError mapHttp(int code,String body){ String msg=limit(body==null?"":body.replaceAll("\\s+"," "),500); String type="HTTP_"+code, sug="请检查接口设置"; if(code==400){type="HTTP_400";sug="请检查模型参数、JSON 格式或 max_tokens 兼容性";} else if(code==401){type="HTTP_401";sug="API Key 无效或已过期";} else if(code==403){type="HTTP_403";sug="接口拒绝访问";} else if(code==404){type="HTTP_404";sug="Base URL 或模型不存在";} else if(code==408){type="HTTP_408";sug="请求超时";} else if(code==429){type="HTTP_429";sug="请求过于频繁或额度不足";} else if(code>=500){type="HTTP_"+code;sug="服务端异常，请稍后重试";} return new AiError(type,"HTTP "+code+"："+msg,sug,code); }
 static String limit(String s,int n){return s==null?"":(s.length()>n?s.substring(0,n):s);} }
