package com.zzy.ksongfloat.classifier;

public enum PageType {
    CITY_USER_LIST,
    NEARBY_LIST,
    RECOMMEND_FEED,
    USER_PROFILE,
    WORK_DETAIL,
    COMMENT_PANEL,
    COMMENT_INPUT,
    PRIVATE_MESSAGE,
    PRIVATE_MESSAGE_INPUT,
    SEARCH_PAGE,
    UNKNOWN_KSONG_PAGE,
    OUTSIDE_TARGET_APP,
    KSONG_SETTINGS,
    ACCOUNT_SETTINGS,
    SECURITY_CENTER,
    SYSTEM_SETTINGS,
    SYSTEM_DIALOG,
    UNKNOWN
}
