package com.zzy.ksongfloat.runtime;

public enum AssistantRuntimeState {
    STOPPED,
    STARTING,
    WAITING_FOR_ACCESSIBILITY,
    WAITING_FOR_TARGET_APP,
    TARGET_APP_DETECTED,
    SUPPORTED_PAGE_DETECTED,
    READY_TO_ANALYZE,
    CAPTURE_PERMISSION_REQUIRED,
    CAPTURING,
    OCR_PROCESSING,
    LOCAL_CLASSIFYING,
    AI_CONFIGURATION_REQUIRED,
    AI_ANALYZING,
    RESULT_READY,
    INPUT_FIELD_READY,
    FILLING_TEXT,
    PAUSED,
    ERROR
}
